ludovicchabant/vim-gutentags

- README.md
I noticed the incomplete link to Pathogen and thought I'd add it. Cheers.
> Added link to pathogen in readme

- plat/unix/update_tags.sh
I pushed something wrong last time I created the fix for the removing of the tags.-Files. I forgot an exit, so the script didn't really stop and the files could remain nevertheless.
> Without an exit in the trap, the remainig commands still get executed.

- autoload/gutentags.vim
- autoload/gutentags/ctags.vim
- doc/gutentags.txt
If, for example, a variable `g:gutentags_ctags_executable_ruby` is found, its value will be used as the ctags executable command for ruby filetype files. Otherwise, it will default to global `g:gutentags_ctags_executable`
My need is to be able to use [ripper-tags](https://github.com/tmm1/ripper-tags) for ruby projects.
Please, if you need some code style or organizational modification feel free to tell me.
> Add the feature to configure ctags executables specific for filetypes

- autoload/gutentags/cscope.vim
- plat/unix/update_scopedb.sh
- plat/win32/update_scopedb.cmd
I saw recently you added cscope support and gave it a try today.
But I believe there a few problems : 
* cscope database are the most useful in the top directory of the project, but as far as I know you need to be in this directory to generate the DB (so I added this part in the unix script but I'm not sure how to do it for Windows sorry :( )
* once the DB has been updated you have to use ```cs reset``` in vim in order to synchronize with the changes (the change for 'neovim' support is here to fix this issue)
* one issue I did not address in this PR, is the fact that the "intial" generation of the database can be quite long (for example in on of my projects it needs about 1/2 minutes) but if you change a few files and re-run the cscope generation with the old data it may only take a few …
> Cscope support for Unix systems

- autoload/gutentags.vim
Use l:markers instead of g:gutentags_project_root as the source of
project root indicators when testing parent directories.
In get_project_root, the list l:markers is built up with the contents of
g:gutentags_project_root and g:ctrlp_root_markers (if it exists).
However, g:gutentags_project_root was used directly while testing for
the presence of project root indicators (l:markers was ignored).
> Use full list of root markers in get_project_root.

- autoload/gutentags/ctags.vim
- plugin/gutentags.vim
Allows "~/..." paths to work.
Also squash verbose code.
> expand() g:gutentags_ctags_executable

- plat/unix/update_tags.sh
Explicitly match the file name in the second tab-delimited column.
Also, add a "|| true" to handle the case where no lines would be
selected by grep (e.g. after `touch tags` and only updating a single
file).
TODO:
I don't know how `findstr /V /C:"%UPDATED_SOURCE%" "%TAGS_FILE%" > "%TAGS_FILE%.temp"`` would need to be modified though.
> Make pattern for removal of existing lines more specific

- autoload/gutentags.vim
- plugin/gutentags.vim
Only set project root finder to blank if not already set and test
explicitly for a non blank setting to see if it has been set.
Even if it was set in .vimrc g:gutentags_project_root_finder was always set blank.
Once it was set it was not being called because it was not being recognised as set.
> Enable Project Root Finder

- autoload/gutentags/gtags_cscope.vim
If g:gutentags_gtags_dbpath is not set, l:db_path would have a slash at the end, like
> ~\test_path\
And on Windows, l:db_file would be
> ~\test_path\\/GTAGS
which makes add_db function broken.
> Fix db path of 'gtags-cscope' module on Windows.

- autoload/gutentags.vim
- autoload/gutentags/cscope.vim
- autoload/gutentags/ctags.vim
This avoids overriding local cwd settings, as vim allows `lcd`
for window-local working directory and neovim supports additionally `tcd`
for tab-local working directory.
> Use scope-local functions

- autoload/gutentags/ctags.vim
Hello,
This is a bug fix for a case where execution of ctags command gets malformed, causing Vim to throw an error due to reserved characters not being properly escaped.
The specific error I've come across is `E194: No alternate file name to substitute for '#'`, due to an Emacs entry `.\#*` in a project's gitignore (populating wildignore through a plugin).
This commit addresses that issue, so that Emacs and Vim users can peacefully co-exist.
edit (2017-01-22):
I would also like to mention that this bug is for the most part silent, and can only be traced if your debugging options are set, or when stepping through the code
The exception to this is the side-effect that you won't be able to save a file in a given repo, without  first getting an E13 error (File exists), having to force write, …
> Bug Fix: escape reserved Vim patterns in wildignore entries.

- autoload/gutentags.vim
When folks have `.git` in their `wildignore`, the `globpath` function will never find a project marker. The fix uses an argument which disables ignoring files with this function.
Fixes an issue where `gutentag#get_project_root` never found a project marker, thus, failing `gutentags#setup_gutentags` and none know the wiser. Once you enable the trace command, it's already too late, hard to debug.
> Don't apply `wildignore` when looking for markers

- plat/unix/update_tags.sh
This allows me to specify a command such as `ag --follow --nocolor --nogroup -g ''`. Otherwise, the `''` gets interpreted as passing two literal single quotes to the command, where I meant for it to pass an empty argument.
> Use eval on file list command in unix tag updater

- autoload/gutentags/ctags.vim
`matchstrpos()` was added to Vim as patch 7.4.1685: http://ftp.vim.org/vim/patches/7.4/7.4.1685
Older but still vendor-supported operating systems (such as Ubuntu 14.04 LTS and derivatives) ship versions of Vim that predate this patch. Replacing `matchstrpos()` allows vim-gutentags to continue to work with these older versions of Vim.
Issue: https://github.com/ludovicchabant/vim-gutentags/issues/114
----
**Note:** I'm not entirely sure what the exact `g:gutentags_file_list_command` setting is supposed to be to configure the file list command with absolute output paths. I tested with:
```vim
let g:gutentags_file_list_command = {
\ 'markers': {
\ '.git': 'git ls-files -co --exclude-standard///absolute',
\ },
\ }
```
Please let me know if this isn't the right setting value for that feature.
> Replace matchstrpos() with match() + split() for backwards compatibility

- autoload/gutentags/cscope.vim
There is a typo in `gutentags#cscope#generate` where `gutentags#get_project_file_list_cmd` was using `l:proj_dir` (undefined) instead of `a:proj_dir`.  This was preventing the scope module from working.
This PR simply corrects the typo.
> Fix cscope generation use of proj_dir

- autoload/gutentags/cscope.vim
- plat/unix/update_scopedb.sh
- plat/win32/update_scopedb.cmd
- As mentioned in #141, using `l:proj_dir` causes an error. This should be fixed immediately.
- Just calling `cscope -R` won't work for Homebrew cscope. It instead raises an error:
```
cscope: no source files found
```
So I used simple `find . -type f`.
- `gutentags#ctags#generate` redirects output to `l:actual_tags_file . '.log'` or `/dev/null`, but `gutentags#cscope#generate` doesn't. It makes the output displays on Vim. So I added logging feature, and updated `plat/win32/update_scopedb.cmd`.
> Fix cscope generation

- .gitignore
This PR adds a .gitignore to supplement the existing .hgignore file to disregard generated tags files.
> Ignore tags files

- autoload/gutentags.vim
caused by 6327f37ab22999943ec925a7c8de8c32be366165
> Fix arguments to gutentags#default_io_cb()

- plat/unix/update_tags.sh
If we clear the project directory when we have a file list, ctags won't ignore the `-L` command and run on only the files provided.
Addresses the issue I brought up here:
https://github.com/ludovicchabant/vim-gutentags/issues/101
> Fix gutentags_file_list_command behavior

- autoload/gutentags/cscope.vim
> Suppress warnings from cscope reset

- plat/unix/update_scopedb.sh
Prepend `eval` and surround `$FILE_LIST_CMD` with double quotes to make sure the command actually works if there are single or double quotes in the command string. 
For example `find . -type f -iname "*.php"'`. That would fail without the `eval` command. Double quotes are usually needed when list or pattern is expected, only in a few situation you can omit them safely so I rather put them for safety.
> Fix file list command in `update_scope.sh`

- doc/gutentags.txt
Add missing parameters, fix typos and remove some whitespaces.
Missing parameters were `g:gutentags_gtags_dbpath` and `g:gutentags_gtags_cscope_executable`.
> Improve docs concerning gtags_cscope module

- autoload/gutentags/ctags.vim
The tags variable need spaces in the path to be literally escaped in order to work.
Using macOS 10.14.6, vim 8.1.1517.
Create the the a project with a space in it's path
```bash
foo="folder space" && mkdir "$foo" && cd "$foo" &&\
git init && echo 'def foo(): return 0' > foo.py &&\
mkdir bar && cd bar && touch bar.py
``` 
The above command create:
```text
folder space/.git
folder space/foo.py
folder space/bar/bar.py
```
Set `folder space/bar/` as the current working directory, the open `bar.py` in `vim`
Without this patch, the command `:tag foo` complains that no tag files can be found:
```
E433: No tags file
E426: tag not found: foo
Press ENTER or type command to continue
```
With the patch,  the command `:tag foo` in `folder space/bar/bar.py` will jump to the `foo()` function in `folder …
> Double escape spaces when setting tags path

- plat/unix/update_tags.sh
The ctags command fails on unix platforms when gutentags is installed in a path containing whitespace (or special characters for the shell).
This fixes that problem by supplying the options file as a separately quoted argument. Unlike #254, this does not introduce a bash dependency.
Fixes #237
> Fix paths with spaces without introducing bash dependency

- plat/unix/update_tags.sh
bad case:
```vim
let g:gutentags_file_list_command = {
\ 'markers': {
\ '.gutentags_markdown': 'ls *.md',
\ },
\ }
```
`ls *.md` has `*`, which needs quotes.
> (fix) update_tags.sh: eval ad quotes

- doc/gutentags.txt
I tried using `.gutctags` but found that my tags file was always coming out empty. I eventually found that this was because ctags wasn't being told to recurse, and a bit more debugging showed that `.gutctags`, if present, overrides the default `ctags_recursive.options` file. I've added a warning to that effect to the docs.
> Include override warning in docs for `.gutctags`
